import { ICall } from "../components/Table/types";
export const calls:ICall[] = [
    {
      id: 1,
      agent: "Agente 1",
      id_agent: 123,
      motive: "Consulta general",
      call_start: 1630593600,
      duration: 300,
      channel: "Llamada",
      score: 8,
    },
    {
      id: 2,
      agent: "Agente 2",
      id_agent: 456,
      motive: "Soporte técnico",
      call_start: 1630604400,
      duration: 420,
      channel: "Llamada",
      score: 7,
    },
    {
      id: 3,
      agent: "Agente 3",
      id_agent: 789,
      motive: "Ventas",
      call_start: 1630615200,
      duration: 180,
      channel: "Chat",
      score: 9,
    },
    {
      id: 4,
      agent: "Agente 4",
      id_agent: 101,
      motive: "Reclamación",
      call_start: 1630626000,
      duration: 600,
      channel: "Llamada",
      score: 6,
    },
    {
      id: 5,
      agent: "Agente 5",
      id_agent: 202,
      motive: "Consulta general",
      call_start: 1630636800,
      duration: 240,
      channel: "Chat",
      score: 8,
    },
    {
      id: 6,
      agent: "Agente 6",
      id_agent: 303,
      motive: "Soporte técnico",
      call_start: 1630647600,
      duration: 480,
      channel: "Llamada",
      score: 7,
    },
    {
      id: 7,
      agent: "Agente 7",
      id_agent: 404,
      motive: "Ventas",
      call_start: 1630658400,
      duration: 360,
      channel: "Chat",
      score: 9,
    },
    {
      id: 8,
      agent: "Agente 8",
      id_agent: 505,
      motive: "Reclamación",
      call_start: 1630669200,
      duration: 720,
      channel: "Llamada",
      score: 6,
    },
    {
      id: 9,
      agent: "Agente 9",
      id_agent: 606,
      motive: "Consulta general",
      call_start: 1630680000,
      duration: 300,
      channel: "Chat",
      score: 8,
    },
    {
      id: 10,
      agent: "Agente 10",
      id_agent: 707,
      motive: "Soporte técnico",
      call_start: 1630690800,
      duration: 600,
      channel: "Llamada",
      score: 7,
    }
  ];